name: philb
channels:
  - conda-forge
  - nodefaults
dependencies:
  - cartopy
  - geocube=0.3.2
  - pykrige=1.5.1
  - scipy
  - xarray
  - numpy
  - matplotlib-base=3.5.3
  - rioxarray
  - scikit-learn
  - geopandas
  - geos
  - proj
  - gdal
  - pandas
  - rasterio
  - shapely
  - joblib
  - r-rgdal
  - r-terra
  - r-raster=3.4_13
  - r-spdep=1.1_11
  - r-sf=1.0_5
  - r-sp=1.4-5
  - r-spatialreg=1.2_1
  - r-tidyverse=1.3.1
  - r-patchwork=1.1.1
  - r-ncdf4=1.17
  - r-codetools=0.2_18
  - libnetcdf
  - netcdf4
  - r-base=4.1.2
